project_id = "fppsotlycinwqsjpoybg"

[functions.moderate-content]
verify_jwt = false

[functions.share-post]
verify_jwt = false

[functions.renew-carreira-pix]
verify_jwt = false

[functions.send-carreira-push]
verify_jwt = false

[functions.asaas-webhook]
verify_jwt = false

[functions.disable-asaas-notifications]
verify_jwt = false

[functions.create-carreira-card-subscription]
verify_jwt = true

[functions.cleanup-asaas-duplicates]
verify_jwt = false

[functions.admin-delete-user]
verify_jwt = true

[functions.admin-delete-assinatura]
verify_jwt = true

# trigger redeploy

